# Generated by Django 4.0.1 on 2022-03-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Proyecto',
        ),
    ]
